### ISSUE TITLE
Welcome to the STM32-emulator club :)

### ISSUE THREAD

**Issue by vintagepc** [nviennot/stm32-emulator#1]
Just figured I'd give a shout out to a fellow STM32 emulator aficionado!

I've been busy extending the STM32 support in QEMU myself through my project https://github.com/vintagepc/MINI404 - perhaps some of it will serve as a useful reference in your endeavors. 

I'll be keeping an eye on this  - Welcome to the rabbit-hole that is hardware emulation :rofl:

**Comment by nviennot** [comment]
I'm looking at https://github.com/vintagepc/MINI404/tree/MINI404/hw/arm/prusa/

Impressive!

I'll add a link to your work in the readme

**Comment by vintagepc** [comment]
Thanks :) I'm sure we'll be running into each other more in the future!
