### ISSUE TITLE
GPIO

### ISSUE THREAD

**Issue by zdebel** [nviennot/stm32-emulator#4]
Great work mate! No idea how to contact you other than an issue here. Is there any way (and if is, sorry I can't find it) where I could manually input a GPIO state? I'm trying to reverse engineer some binary blob, and it's waiting for a pin change. I could code in an ext_device but I don't speak RUST.

**Comment by nviennot** [comment]
This would be a useful feature. No doubt. But unfortunately I don't have cycles to put into this project at the moment.

You are now left with the appealing idea of learning Rust...
